config/routes.rb
Rails.application.routes.draw do
  resources :crews
  resources :events
  resources :groups
  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crew.rb
class Crew < ApplicationRecord
    belongs_to :group
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :group

    validates :date, presence: true
    validates :participant, presence: true
    validates :duration, presence: true
end

app/models/group.rb
class Group < ApplicationRecord

    has_many :events, dependent: :destroy
    has_many :crews, dependent: :destroy
    accepts_nested_attributes_for :events
    accepts_nested_attributes_for :crews
    enum gender: { BoyBand: 0, GirlBand: 1, Band: 3 }

    validates :name, presence: true
    validates :debut_date, presence: true
    validates :gender, presence: true
    validates :member, presence: true

    def to_s
        name
    end

    def events_count
        total_events = 0
        self.events.each do |event|
            total_events += 1
        end 
        total_events
    end

    def current_events
        this_month = Time.now.month
        currently_events = 0 
        self.events.each do |event|
            if event.date.month == this_month
                currently_events += 1 
            end 
        end 
        currently_events 
    end

    def last_events
        last_date = Date.new(0000-00-0)
        self.events.each do |event|
            if event.date > last_date
                last_date = event.date
            end
        end
        if last_date != (0-0-0)
            last_date.strftime("%Y %B %A")
        else
            nil
        end
    end

    def max_part
        max_count = 0
        self.events.each do |event| 
            if event.participant > max_count 
            max_count = event.participant 
            end 
        end 
        max_count 
    end

    def long_event
        longest_event = 0 
        self.events.each do |event| 
            if event.duration > longest_event
                longest_event = event.duration
            end 
        end 
        longest_event 
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews or /crews.json
  def index
    @crews = Crew.all
  end

  # GET /crews/1 or /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews or /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1 or /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1 or /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.includes(:group)
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @groups = Group.all
  end

  # GET /events/1/edit
  def edit
    @groups = Group.all
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @groups = Group.all

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:date, :participant, :duration, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_selects, only: %i[new edit create update] 

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:events)
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.events.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:member, :debut_date, :gender, :name, {events_attributes: [:id, :date, :participant, :duration, :_destroy], crews_attributes: [:id, :name]})
    end

    def set_selects 
      @genders= Group.genders.keys.to_a 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/crews/_form.html.erb
<%= form_with(model: crew, local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :participant %>
    <%= form.number_field :participant %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Participant</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.group%></td>
        <td><%= event.date %></td>
        <td><%= event.participant %></td>
        <td><%= event.duration %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Go to groups', groups_path %>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Band:</strong>
  <%= @event.group %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @event.participant %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/groups/_crew_fields.html.erb
<li class="control-group nested-fields">
    <div class="controls">
        <%= f.fields_for :group do |crew_group| %>
            <%= crew_group.text_field :name %>
        <% end %>

        <%= link_to_remove_association "Remove", f %>
    </div>
</li>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :member %>
    <%= form.number_field :member %>
  </div>

  <div class="field">
    <%= form.label :debut_date %>
    <%= form.date_select :debut_date %>
  </div>

  <div class="field">
    <%= form.label :gender, "Gender" %>
    <%= form.select :gender, options_for_select(@genders) %>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Member</th>
      <th>Debut date</th>
      <th>Gender</th>
      <th>Total Events</th>
      <th>Part. Per Event</th>
      <th>Concert ID</th>
      <th>Concert Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.member %></td>
        <td><%= group.debut_date %></td>
        <td><%= group.gender %></td>
        <td><%= group.events_count %></td>
        <td>
          <ul>
            <% group.events.each do |event| %>
              <li><%= event.participant %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% group.events.each do |event| %>
              <li><%= event.id %></li>
            <% end %>
          </ul>
        </td>
        <td>
          <ul>
            <% group.events.each do |event| %>
              <li><%= event.date %></li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Go to events', events_path %>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= form_with(model: @group, local: true) do |form| %>
    <% if @group.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :member %>
        <%= form.number_field :member %>
    </div>

    <div class="field">
        <%= form.label :debut_date %>
        <%= form.date_select :debut_date %>
    </div>

    <div class="field">
        <%= form.label :gender, "Gender" %>
        <%= form.select :gender, options_for_select(@genders) %>
    </div> 

        <h3>First event with us:</h3>

        <%= form.fields_for :events do |event_form| %>
        <div class="field">
            <%= event_form.label :date %>
            <%= event_form.date_select :date %>
        </div>

        <div class="field">
            <%= event_form.label :participant %>
            <%= event_form.number_field :participant %>
        </div>

        <div class="field">
            <%= event_form.label :duration %>
            <%= event_form.number_field :duration %>
        </div> 
        <% end %>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Member:</strong>
  <%= @group.member %>
</p>

<p>
  <strong>Debut date:</strong>
  <%= @group.debut_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @group.gender %>
</p>

<p>
  <strong>Currently events:</strong>
  <%= @group.current_events %>
</p>

<p>
  <strong>Last event:</strong>
  <%= @group.last_events %>
</p>

<p>
  <strong>Maxium participants:</strong>
  <%= @group.max_part %>
</p>

<p>
  <strong>Longest Event:</strong>
  <%= @group.long_event %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>